apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: Qolzam-secrets
  namespace: openfaas-fn
spec:
  encryptedData:
    email: AgAhvqysnVbbNvR2eCOJ+hOWG3GMFKDPW1NNwKOEsfLLcNZ/vrtr9X2mwH7NF5drxn546SJ+9BulM73VrQklyV4cG+GAc5sjTMwWzqTrwiTXU0nYFRPukoqO8q0CeaGyKLwPdKKepsxIm9C5aYLAHSKFkbrFbmwwRfTpdWrvAFUw2/wvDa+5hWXYYkrl2ao8IIagnMDh8GWHrGZyY7hluga7EwZ9N3tb80epsSatbXqc7yUiUXhQ4/XYDfFdSgpdm9ew8VglqcRcb8kkFbPJW8vCBVfVJvpGc1d6VKz7L+upaI4IKC1hdxLIpLVr5FgveUMjnFDN7mvABwNiJzGnPwEKR42m2jd0ajtDJa1z4kOYSkx5L89lp4q7+p3LJqKeFO+Lx7+U6MBhEac+PE5b3tiZZsBUMCcKM1bvL0HGzcwbiHHJCTHi1KKx6/TZnHrpAQ1RGne8ASu5YIVHkGXtgLEhApW+znypGi6S8enr/gh8oEKEyu2h8E101UgfNeXyYtHYanEayMbqD1/C6pwKe96hfTk1biSmRRnprvBAe1RwE92s6DkA0HzLiQSpMkjAqxrpibIppOAgyV4yvhRdU8D/lMhqMlbvLdZScP8CqQq8pk2r2+r82TAlzrVEC8I4vUS89BK0TeHf/lCSWVk131Yn3LDTbf6KrJgK8u6y3agSE04ZhEEW8P6K1K1bY7qdUy53KbXLk6f7cBuzE2i7hqOidiC186F4CmI=
    password: AgAKrIN3cDqD0kQT/+6MzV3d8e89fTJgSEGxV0ZIUUG/W2WD/CVxoeMgEErjmzb+G/KHOE8ZlAu8WB4rIew+glhe1WX3GfSvLS6kdRefXc6Nk2DPcuDrP4TbKBOdXqq4UYH41G7O3SN0PHXAHuZrWpnxYe/q5olnrAgrGycYhmxztZImmBpmPI2nQPCglLX4uMiep5GRKTRzPVDoaBRxUQ2dEdZzlMv7S9VAkx26TZ63l7khSblYFN3mGKbsa7jyCybdFtQoRmkPf0U/fDn+LNDPM3Y86cZX1SP48J3pRne5dZ8xUYdfQAlxq++0KclxWKRyp/KIfqhdu9arDDFsruEu4qFJhm45DDSzq+XgwHRqNWGHQOGCCL2U5qFLK4l9yP5a1tshxLZZUSqsWByfBy6zNyCzW2Ljzg81cIDEZKhTNau/fOWsis/pawZPVnx1gUW2X3dwSQr3IuVF9+X/MooTes/chyRX+93TXlo0q0sHxFn5iki48LTaE8Ir/h6v6X1KgQvPpvFg2YGWZOIeWJsrSH3SAbK/gFZCizbrY0+VUQB/G2R6XG58RKBxXJncmcp/mFYeg8gLZB0TlMIQujF8FmSNMJWH5T+LL5n0NimzYdFLHn+apEgiq8VUs1LCXCcG0dDCXN0bSDBlX2GMtveBqNn4q/xT4sn6mfKD/bpoL3COt3I51ZbAqq/oJRwhxqck7EU1eCoguVXKAQ==
  template:
    metadata:
      creationTimestamp: null
      name: Qolzam-secrets
      namespace: openfaas-fn
status: {}

