version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:31112
functions:
  email-fn:
    lang: node12
    handler: ./email-fn
    image: email-fn:latest
    labels: 
        com.openfaas.scale.zero: false
    environment:
        content_type: "application/json"
    secrets:
      - secrets
